-- ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
-- บ    Package  TVGRAF  Graphic extension GNAT OS/2               บ
-- บ      file system screen connection                            บ
-- บ                                                               บ
-- บ  Author: Leonid Dulman                                        บ
-- บ                                                               บ
-- บ                       1996                                    บ
-- บ                                                               บ
-- ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ

package  tvgraph is

procedure open_tabl;
procedure close_tabl;
procedure blank(s:in out string;n_tab:integer);
----------------------------------------------------------------
end tvgraph;
