   #define MIS_TEXT                   0x0001
   #define MIS_BITMAP                 0x0002
   #define MIS_SEPARATOR              0x0004
   #define MIS_OWNERDRAW              0x0008
   #define MIS_SUBMENU                0x0010
   #define MIS_MULTMENU               0x0020
   #define MIS_SYSCOMMAND             0x0040
   #define MIS_HELP                   0x0080
   #define MIS_STATIC                 0x0100
   #define MIS_BUTTONSEPARATOR        0x0200
   #define MIS_BREAK                  0x0400
   #define MIS_BREAKSEPARATOR         0x0800
   #define MIS_GROUP                  0x1000





